graph TD
  A(Mulai) --> B[Admin Prodi melakukan login]
  B --> C[Admin mengaktifkan slider aktif kerja]
  C --> D[Admin menunggu input mahasiswa]
  D --> E[/Mahasiswa dipanggil sesuai antrian/]
  E --> F(Selesai)